/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package installmentcenter;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class Addcustomers extends javax.swing.JFrame {

    /**
     * Creates new form AddcostomerRecords
     */
    public Addcustomers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        cnic = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        accNumber = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Customer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 10, 176, 27);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 50, 52, 24);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Father's Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 100, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 260, 91, 37);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CNIC");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 150, 113, 35);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(335, 45, 254, 37);
        getContentPane().add(address);
        address.setBounds(335, 255, 254, 36);

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        getContentPane().add(fname);
        fname.setBounds(335, 95, 254, 36);

        cnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicActionPerformed(evt);
            }
        });
        getContentPane().add(cnic);
        cnic.setBounds(335, 147, 254, 35);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(120, 360, 100, 50);

        save.setBackground(new java.awt.Color(0, 0, 0));
        save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(310, 360, 100, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(343, 137, 0, 0);
        getContentPane().add(cNumber);
        cNumber.setBounds(335, 199, 254, 37);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Contact Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 200, 101, 37);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Account Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 320, 102, 15);
        getContentPane().add(accNumber);
        accNumber.setBounds(335, 311, 254, 36);

        Clear.setBackground(new java.awt.Color(0, 0, 0));
        Clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear);
        Clear.setBounds(490, 360, 100, 50);

        setSize(new java.awt.Dimension(716, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        }); // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        ArrayList<Customers> customer =new LoadCustomers().getdata();
        FileWriter fw=null;
        BufferedWriter bw=null;
        if("".equals(name.getText()) || "".equals(accNumber.getText()) || "".equals(address.getText()) || "".equals(fname.getText())|| "".equals(cnic.getText())|| "".equals(cNumber.getText()))
        {
            JOptionPane.showMessageDialog(this,"Field Cannot be Empty!");

        }
        else
        {
            Customers obj1=new Customers(name.getText(),fname.getText(),cnic.getText(),address.getText(),cNumber.getText(),accNumber.getText(),"0","0","0","0","0",new ArrayList<Product>());
            customer.add(obj1);
            try{
               fw=new FileWriter("customer.txt");
                bw=new BufferedWriter(fw);
                for(int i=0;i<customer.size();i++)
                {
                    Customers obj=customer.get(i);
                    bw.write(obj.getName()+" "+obj.getFather()+" "+obj.getCnic()+" "+obj.getAddress()+" "+obj.getContact()+" "+obj.getAccountnum()+" "+obj.getInterest()+" "+obj.getInterestamount()+" "+obj.getMonthlyamount()+" "+obj.getDateofpurchasing()+" "+obj.getDateofending()+" "+obj.getBuyProduct().size());
                    for(int j=0;j<obj.getBuyProduct().size();j++){
                        Product obj2=obj.getBuyProduct().get(j);
                        bw.newLine();
                        bw.write(obj2.getName()+" "+obj2.getCompany_name()+" "+obj2.getPrice()+" "+obj2.getQuantity()+" "+0+" "+obj2.getInstalment().size());
                        for(int k=0;k<obj2.getInstalment().size();k++)
                        {
                            Instalment obj3=obj2.getInstalment().get(k);
                            bw.newLine();
                            bw.write(obj3.getMonthly()+" "+obj3.getRemaning()+" "+obj3.getDate());
                        }
                        
                    }
                    bw.newLine();
                    
                }
                bw.close();
                fw.close();

            }catch(IOException e)
            {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(this,"Customer Added Successfully!");
        }
    }//GEN-LAST:event_saveActionPerformed

    private void cnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        name.setText("");
        fname.setText("");
        cnic.setText("");
        accNumber.setText("");
        cNumber.setText("");
        address.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JTextField accNumber;
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JTextField cNumber;
    private javax.swing.JTextField cnic;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField name;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
