package installmentcenter;

import java.awt.Toolkit;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage()  
    {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employee = new javax.swing.JButton();
        products = new javax.swing.JButton();
        costumer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        employee.setBackground(new java.awt.Color(0, 0, 0));
        employee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        employee.setForeground(new java.awt.Color(255, 255, 255));
        employee.setText("Employee");
        employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeActionPerformed(evt);
            }
        });
        getContentPane().add(employee);
        employee.setBounds(240, 120, 215, 50);

        products.setBackground(new java.awt.Color(0, 0, 0));
        products.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        products.setForeground(new java.awt.Color(255, 255, 255));
        products.setText("Products");
        products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsActionPerformed(evt);
            }
        });
        getContentPane().add(products);
        products.setBounds(240, 180, 215, 50);

        costumer.setBackground(new java.awt.Color(0, 0, 0));
        costumer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        costumer.setForeground(new java.awt.Color(255, 255, 255));
        costumer.setText("Customer");
        costumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costumerActionPerformed(evt);
            }
        });
        getContentPane().add(costumer);
        costumer.setBounds(240, 240, 215, 50);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("PRODUCTS INSTALLMENTS MANAGEMENT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 20, 590, 60);

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(10, 370, 100, 40);

        setSize(new java.awt.Dimension(696, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsActionPerformed
 dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_productsActionPerformed

    private void employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeActionPerformed
            dispose();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });// TODO add your handling code here:
    }//GEN-LAST:event_employeeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
       dispose();
       java.awt.EventQueue.invokeLater(new Runnable(){
                   public void run(){
                       new LogIn().setVisible(true);
                   }
               } );
    }//GEN-LAST:event_logoutActionPerformed

    private void costumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costumerActionPerformed
        dispose();
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_costumerActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton costumer;
    private javax.swing.JButton employee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton products;
    // End of variables declaration//GEN-END:variables
}
