/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package installmentcenter;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class DelCustomer extends javax.swing.JFrame {

    /**
     * Creates new form DelCustomer
     */
    public DelCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        accnumber = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        delRecord = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Delete Record");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 20, 168, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 120, 102, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Account Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 200, 102, 30);
        getContentPane().add(accnumber);
        accnumber.setBounds(308, 196, 254, 32);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(120, 290, 110, 50);

        delRecord.setBackground(new java.awt.Color(0, 0, 0));
        delRecord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delRecord.setForeground(new java.awt.Color(255, 255, 255));
        delRecord.setText("Delete");
        delRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delRecordActionPerformed(evt);
            }
        });
        getContentPane().add(delRecord);
        delRecord.setBounds(290, 290, 110, 50);
        getContentPane().add(name);
        name.setBounds(308, 114, 254, 36);

        Clear.setBackground(new java.awt.Color(0, 0, 0));
        Clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear);
        Clear.setBounds(450, 290, 110, 50);

        setSize(new java.awt.Dimension(696, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         dispose();
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void delRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delRecordActionPerformed
        ArrayList<Customers> customer=new LoadCustomers().getdata();
         Boolean flag=false;
         for(int i=0;i<customer.size();i++)
         {
             if(name.getText().contains(customer.get(i).getName())&&accnumber.getText().contains(customer.get(i).getAccountnum()))
             {
                 customer.remove(i);
                 JOptionPane.showMessageDialog(this,"Customer Deleted Successfully");
                 flag=true;
                 break;
             }
         }
             if(flag==false)
             {
                 JOptionPane.showMessageDialog(this,"No Customer Found!");
             }
             if(flag==true){
         FileWriter fw=null;
         BufferedWriter bw=null;
           try{
                fw=new FileWriter("customer.txt");
                bw=new BufferedWriter(fw);
                for(int i=0;i<customer.size();i++)
                {
                    Customers obj=customer.get(i);
                    bw.write(obj.getName()+" "+obj.getFather()+" "+obj.getCnic()+" "+obj.getAddress()+" "+obj.getContact()+" "+obj.getAccountnum()+" "+obj.getInterest()+" "+obj.getInterestamount()+" "+obj.getMonthlyamount()+" "+obj.getDateofpurchasing()+" "+obj.getDateofending()+" "+obj.getBuyProduct().size());
                    for(int j=0;j<obj.getBuyProduct().size();j++){
                        Product obj2=obj.getBuyProduct().get(j);
                        bw.newLine();
                        bw.write(obj2.getName()+" "+obj2.getCompany_name()+" "+obj2.getPrice()+" "+obj2.getQuantity()+" "+0+" "+obj2.getInstalment().size());
                        for(int k=0;k<obj2.getInstalment().size();k++)
                        {
                            Instalment obj3=obj2.getInstalment().get(k);
                            bw.newLine();
                            bw.write(obj3.getMonthly()+" "+obj3.getRemaning()+" "+obj3.getDate());
                        }
                        
                    }
                    bw.newLine();
                    
                }
                bw.close();
                fw.close();


            }catch(IOException e)
            {
                e.printStackTrace();
            }
             }
        // TODO add your handling code here:
    }//GEN-LAST:event_delRecordActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        name.setText("");
        accnumber.setText("");
        
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JTextField accnumber;
    private javax.swing.JButton back;
    private javax.swing.JButton delRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
