/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package installmentcenter;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class DelEmployee extends javax.swing.JFrame {

    /**
     * Creates new form DelEmpRecord
     */
    public DelEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        cnic = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        DelEmployee = new javax.swing.JButton();
        Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Delete Employee Record");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 292, 38);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 130, 44, 37);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("CNIC");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(122, 194, 30, 15);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(250, 130, 300, 29);
        getContentPane().add(cnic);
        cnic.setBounds(249, 187, 300, 29);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(120, 280, 110, 49);

        DelEmployee.setBackground(new java.awt.Color(0, 0, 0));
        DelEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DelEmployee.setForeground(new java.awt.Color(255, 255, 255));
        DelEmployee.setText("Delete Employee");
        DelEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelEmployeeActionPerformed(evt);
            }
        });
        getContentPane().add(DelEmployee);
        DelEmployee.setBounds(270, 280, 133, 49);

        Clear.setBackground(new java.awt.Color(0, 0, 0));
        Clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear);
        Clear.setBounds(440, 280, 110, 50);

        setSize(new java.awt.Dimension(696, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void DelEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelEmployeeActionPerformed
       ArrayList<Employees> employee=new LoadEmployees().getdata();
         Boolean flag=false;
         for(int i=0;i<employee.size();i++)
         {
             if(name.getText().contains(employee.get(i).getName())&&cnic.getText().contains(employee.get(i).getCnic()))
             {
                 employee.remove(i);
                 JOptionPane.showMessageDialog(this,"Employee Deleted Successfully");
                 flag=true;
                 break;
             }
         }
             if(flag==false)
             {
                 JOptionPane.showMessageDialog(this,"No Employee Found!");
             }
         FileWriter fw=null;
         BufferedWriter bw=null;
         try{
             fw=new FileWriter("employee.txt");
             bw=new BufferedWriter(fw);
             for(int i=0;i<employee.size();i++)
             {
                 Employees obj=employee.get(i);
                 bw.write(obj.getName()+" "+ obj.getfathername()+" "+ obj.getCnic()+" "+ obj.getAddress()+" "+ obj.getContact()+" "+ obj.getSalary());
                 bw.newLine();
             }
             bw.close();
             fw.close();
         }catch(IOException e)
         {
              e.printStackTrace();
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_DelEmployeeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       dispose();
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });  
      // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        name.setText("");
        cnic.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton DelEmployee;
    private javax.swing.JButton back;
    private javax.swing.JTextField cnic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
