/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package installmentcenter;


public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addemployee = new javax.swing.JButton();
        remployee = new javax.swing.JButton();
        employee = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        addemployee.setBackground(new java.awt.Color(0, 0, 0));
        addemployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addemployee.setForeground(new java.awt.Color(255, 255, 255));
        addemployee.setText("Add Employee");
        addemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addemployeeActionPerformed(evt);
            }
        });
        getContentPane().add(addemployee);
        addemployee.setBounds(260, 130, 143, 50);

        remployee.setBackground(new java.awt.Color(0, 0, 0));
        remployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remployee.setForeground(new java.awt.Color(255, 255, 255));
        remployee.setText("Remove Employee");
        remployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remployeeActionPerformed(evt);
            }
        });
        getContentPane().add(remployee);
        remployee.setBounds(260, 200, 143, 50);

        employee.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        employee.setText("Employee");
        getContentPane().add(employee);
        employee.setBounds(270, 0, 120, 90);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(10, 350, 92, 49);

        setSize(new java.awt.Dimension(696, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addemployeeActionPerformed
           dispose();
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployee().setVisible(true);
            }
        }); // TODO add your handling code here:
    }//GEN-LAST:event_addemployeeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
      dispose();
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });  // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void remployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remployeeActionPerformed
             dispose();
             java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DelEmployee().setVisible(true);
            }
        }); // TODO add your handling code here:
    }//GEN-LAST:event_remployeeActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addemployee;
    private javax.swing.JButton back;
    private javax.swing.JLabel employee;
    private javax.swing.JButton remployee;
    // End of variables declaration//GEN-END:variables
}
