/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package installmentcenter;

import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class SearchProducts extends javax.swing.JFrame {

    /**
     * Creates new form SearchProducts
     */
    public SearchProducts() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        companyName = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        searchProducts = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sname = new javax.swing.JLabel();
        scompany = new javax.swing.JLabel();
        squantity = new javax.swing.JLabel();
        sprice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Search Products");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 10, 169, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 60, 75, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Company Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 100, 15);
        getContentPane().add(name);
        name.setBounds(201, 49, 190, 30);
        getContentPane().add(companyName);
        companyName.setBounds(200, 90, 190, 30);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(30, 360, 90, 40);

        searchProducts.setBackground(new java.awt.Color(0, 0, 0));
        searchProducts.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchProducts.setForeground(new java.awt.Color(255, 255, 255));
        searchProducts.setText("Search");
        searchProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProductsActionPerformed(evt);
            }
        });
        getContentPane().add(searchProducts);
        searchProducts.setBounds(410, 90, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Company Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 238, 100, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 213, 42, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 292, 60, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Price");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 267, 42, 15);

        sname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(sname);
        sname.setBounds(201, 213, 158, 14);

        scompany.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(scompany);
        scompany.setBounds(201, 238, 158, 14);

        squantity.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(squantity);
        squantity.setBounds(201, 292, 158, 19);

        sprice.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(sprice);
        sprice.setBounds(201, 269, 150, 12);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Searched Item");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 130, 187, 72);

        Clear.setBackground(new java.awt.Color(0, 0, 0));
        Clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear);
        Clear.setBounds(150, 360, 90, 40);

        setSize(new java.awt.Dimension(661, 447));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
dispose();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void searchProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProductsActionPerformed
    ArrayList<Product> product=new LoadProducts().getdata();
    Boolean flag=false;
    for(int i=0 ; i<product.size();i++)
    {
     if(name.getText().contains(product.get(i).getName())&& companyName.getText().contains(product.get(i).getCompany_name()))
     {
         sname.setText(product.get(i).getName());
         scompany.setText(product.get(i).getCompany_name());
         sprice.setText(product.get(i).getPrice()+"");
         squantity.setText(product.get(i).getQuantity()+"");
         flag=true;
         break;
     }   
    }
    if(flag==false)
    {
         JOptionPane.showMessageDialog(this,"No Product Found!");
    }
    }//GEN-LAST:event_searchProductsActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
       name.setText("");
       companyName.setText("");
       sname.setText("");
       scompany.setText("");
       sprice.setText("");
       squantity.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton back;
    private javax.swing.JTextField companyName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField name;
    private javax.swing.JLabel scompany;
    private javax.swing.JButton searchProducts;
    private javax.swing.JLabel sname;
    private javax.swing.JLabel sprice;
    private javax.swing.JLabel squantity;
    // End of variables declaration//GEN-END:variables
}
