/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package installmentcenter;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class UpdtadeProducts extends javax.swing.JFrame {

    /**
     * Creates new form UpdtadeProducts
     */
    public UpdtadeProducts() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        company = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        uquantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ucompany = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        uprice = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Update Products");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(267, 11, 159, 22);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(38, 91, 40, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Company Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(38, 129, 94, 15);
        getContentPane().add(name);
        name.setBounds(180, 80, 400, 30);
        getContentPane().add(company);
        company.setBounds(180, 130, 400, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Updates To Be Made");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 165, 142, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Product To Be Updated");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 48, 162, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(36, 324, 75, 15);

        uquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uquantityActionPerformed(evt);
            }
        });
        getContentPane().add(uquantity);
        uquantity.setBounds(180, 320, 398, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 210, 75, 15);
        getContentPane().add(uname);
        uname.setBounds(180, 200, 400, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Company Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 250, 94, 15);
        getContentPane().add(ucompany);
        ucompany.setBounds(180, 240, 398, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Price");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 290, 75, 15);

        uprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upriceActionPerformed(evt);
            }
        });
        getContentPane().add(uprice);
        uprice.setBounds(180, 280, 398, 30);

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(250, 360, 130, 40);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(40, 360, 130, 38);

        Clear.setBackground(new java.awt.Color(0, 0, 0));
        Clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Clear.setForeground(new java.awt.Color(255, 255, 255));
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear);
        Clear.setBounds(450, 360, 130, 40);

        setSize(new java.awt.Dimension(696, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uquantityActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
 dispose();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
         ArrayList<Product> product=new LoadProducts().getdata();
         Boolean flag=false;
         for(int i=0;i<product.size();i++)
         {
             if(name.getText().contains(product.get(i).getName())&&company.getText().contains(product.get(i).getCompany_name()))
             {
                   String name=uname.getText();
                   String comp=ucompany.getText();
                   float pric=Float.parseFloat(uprice.getText());
                   int qunty=Integer.parseInt(uquantity.getText());
                   Product obj=new Product(name,pric,qunty,comp,0,null);
                   product.remove(i);
                   product.add(i, obj);
                   JOptionPane.showMessageDialog(this,"Updated Successfully");
                   flag=true;
                   break;
             }
         }
          if(flag==false)
             {
                 JOptionPane.showMessageDialog(this,"No Product Found!");
             }
         FileWriter fw=null;
         BufferedWriter bw=null;
         try{
             fw=new FileWriter("product.txt");
             bw=new BufferedWriter(fw);
             for(int i=0;i<product.size();i++)
             {
                 Product obj=product.get(i);
                bw.write(obj.getName()+" "+obj.getCompany_name()+" "+obj.getPrice()+" "+obj.getQuantity());
                bw.newLine();
             }
             bw.close();
             fw.close();
         }catch(Exception e)
         {
             
         }
         
    }//GEN-LAST:event_updateActionPerformed

    private void upriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upriceActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        name.setText("");
        company.setText("");
        uname.setText("");
        ucompany.setText("");
        uprice.setText("");
        uquantity.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton back;
    private javax.swing.JTextField company;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField ucompany;
    private javax.swing.JTextField uname;
    private javax.swing.JButton update;
    private javax.swing.JTextField uprice;
    private javax.swing.JTextField uquantity;
    // End of variables declaration//GEN-END:variables
}
